name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: linux install cmake
      run: sudo apt-get install -y cmake
    - name: build
      run: ./build.sh
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
